[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build-with-cargo]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build-with-act]
command = "act"
args = ["--job build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.run-raze]
command = "bazelisk"
args = ["run", "@cargo_raze//:raze", "--", "--manifest-path=$$PWD/language/modules/parser/Cargo.toml"]
dependencies = ["clean"]

[tasks.run-blackjack]
description = "Build Rust dependencies graph"
command = "bazelisk"
args = ["run", "//:blackjack"]
dependencies = ["clean"]

[tasks.say-hello]
script = [
    "echo hello"
]