[book]
title = "Fumbo In-Depth"
authors = ["Handcrafted since 2022 by Fumbo sorcerers"]
multilingual = false
language = "en"
src = "contents"

[build]
build-dir="../../target/documents/book"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

#[output.katex]

#[preprocessor.katex]
#macros = "macros.txt"