name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # Virtual environment (no need to install Bazel and Bazelisk as they are already supported in virtual environments)
    runs-on: ubuntu-latest

    steps:
      - name: Extract source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      #
      - name: Install Cargo Make tool
        uses: davidB/rust-cargo-make@v1
        with:
          version: latest

        # Cache and restore Bazel downloads
      - name: Restore Bazel cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: bazel-${{ hashFiles('.bazelversion') }}

      - name: Restore Cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            cargo/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('cargo/**/Cargo.lock') }}

      - name: Build project code
        run: cargo make build
